### ISSUE TITLE
is there a way to talk a file system recursivly?

### ISSUE THREAD

**Issue by TwoClocks** [unmade/audiomatch#22]
My audio files are split up across directories in the form of [artist]/[album] etc. So spread across hundreds of directories. How do I just compare all the files anywhere in the directory tree?

**Comment by unmade** [comment]
the program supports wildcards in path, so you can do as follows:

```bash
audiomatch  "./your_directory/*"
```

That should start comparing everything with everything. Keep in mind it will take long time if the directory is quite large. Feel free to open you have any questions
